spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/katatest-shopping
    username: postgres
    password: osm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8091
     