spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/katatest-user
    username: postgres
    password: osm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cloud:
  gateway:
    routes:
      - id: product-service
        uri: http://localhost:8092
        predicates:
          - Path=/api/katatest/product/**
      - id: cart-service
        uri: http://localhost:8091
        predicates:
          - Path=/api/katatest/cart/**



server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/








     