
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/katatest-product
    username: postgres
    password: osm
    driver-class-name: org.postgresql.Driver

  cloud.loadbalancer.enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  main:
    allow-bean-definition-overriding: true

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

