spring:
  application:
    name: cart-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


  datasource:
    url: jdbc:postgresql://localhost:5432/katatest-shopping
    username: postgres
    password: osm
    driver-class-name: org.postgresql.Driver

    cloud:
      discovery:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8091


     